package com.receiptvault.service;

import com.receiptvault.entity.Receipt;
import com.resend.Resend;
import com.resend.core.exception.ResendException;
import com.resend.services.emails.model.CreateEmailOptions;
import com.resend.services.emails.model.CreateEmailResponse;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
public class EmailService {

    @Value("${RESEND_API_KEY:}")
    private String resendApiKey;

    @Value("${RECEIPT_EMAIL:}")
    private String recipientEmail;

    public void sendReceiptEmail(Receipt receipt) {
        if (resendApiKey == null || resendApiKey.isEmpty()) {
            System.out.println("Resend API key not configured — skipping email.");
            return;
        }

        try {
            Resend resend = new Resend(resendApiKey);

            String propertyAddress = receipt.getProperty() != null ?
                    receipt.getProperty().getAddress() : "Unknown Property";
            String subject = "Receipt #" + receipt.getReceiptID() +
                    " — " + propertyAddress;

            CreateEmailOptions params = CreateEmailOptions.builder()
                    .from("ReceiptVault <onboarding@resend.dev>")
                    .to(recipientEmail)
                    .subject(subject)
                    .html(buildEmailBody(receipt))
                    .build();

            CreateEmailResponse data = resend.emails().send(params);
            System.out.println("Email sent successfully — ID: " + data.getId());

        } catch (ResendException e) {
            System.err.println("Failed to send email: " + e.getMessage());
        }
    }

    private String buildEmailBody(Receipt receipt) {
        return """
                <div style='font-family:Arial,sans-serif; max-width:600px; margin:0 auto;'>
                    <div style='background:#1A1F2E; padding:24px; border-radius:8px 8px 0 0;'>
                        <h1 style='color:white; margin:0; font-size:22px;'>🧾 ReceiptVault</h1>
                        <p style='color:rgba(255,255,255,0.6); margin:4px 0 0;'>Receipt Notification</p>
                    </div>
                    <div style='background:#F7F8FC; padding:24px; border:1px solid #E2E6F0;'>
                        <h2 style='color:#1A1F2E; margin:0 0 16px;'>Receipt #%d</h2>
                        <table style='width:100%%; border-collapse:collapse;'>
                            <tr style='background:white;'>
                                <td style='padding:10px 14px; border:1px solid #E2E6F0; font-size:12px; color:#888; font-weight:bold; text-transform:uppercase;'>Business</td>
                                <td style='padding:10px 14px; border:1px solid #E2E6F0; font-size:14px;'>%s</td>
                            </tr>
                            <tr style='background:#FAFBFF;'>
                                <td style='padding:10px 14px; border:1px solid #E2E6F0; font-size:12px; color:#888; font-weight:bold; text-transform:uppercase;'>Property</td>
                                <td style='padding:10px 14px; border:1px solid #E2E6F0; font-size:14px;'>%s</td>
                            </tr>
                            <tr style='background:white;'>
                                <td style='padding:10px 14px; border:1px solid #E2E6F0; font-size:12px; color:#888; font-weight:bold; text-transform:uppercase;'>Address</td>
                                <td style='padding:10px 14px; border:1px solid #E2E6F0; font-size:14px;'>%s</td>
                            </tr>
                            <tr style='background:#FAFBFF;'>
                                <td style='padding:10px 14px; border:1px solid #E2E6F0; font-size:12px; color:#888; font-weight:bold; text-transform:uppercase;'>Date</td>
                                <td style='padding:10px 14px; border:1px solid #E2E6F0; font-size:14px;'>%s</td>
                            </tr>
                            <tr style='background:white;'>
                                <td style='padding:10px 14px; border:1px solid #E2E6F0; font-size:12px; color:#888; font-weight:bold; text-transform:uppercase;'>Amount</td>
                                <td style='padding:10px 14px; border:1px solid #E2E6F0; font-size:18px; font-weight:bold; color:#1A1F2E;'>$%s</td>
                            </tr>
                            %s
                        </table>
                    </div>
                    <div style='background:#1A1F2E; padding:16px 24px; border-radius:0 0 8px 8px; text-align:center;'>
                        <p style='color:rgba(255,255,255,0.5); font-size:12px; margin:0;'>
                            Generated by ReceiptVault &nbsp;·&nbsp; %s
                        </p>
                    </div>
                </div>
                """.formatted(
                receipt.getReceiptID(),
                receipt.getBusiness() != null ? receipt.getBusiness().getBusinessName() : "—",
                receipt.getProperty() != null ? receipt.getProperty().getPropertyName() : "—",
                receipt.getProperty() != null ? receipt.getProperty().getAddress() + ", " +
                        receipt.getProperty().getCity() + ", " +
                        receipt.getProperty().getState() + " " +
                        receipt.getProperty().getZipCode() : "—",
                receipt.getReceiptDate(),
                receipt.getAmount().toPlainString(),
                receipt.getNotes() != null && !receipt.getNotes().isEmpty() ?
                        "<tr style='background:#FAFBFF;'><td style='padding:10px 14px; border:1px solid #E2E6F0; font-size:12px; color:#888; font-weight:bold; text-transform:uppercase;'>Notes</td><td style='padding:10px 14px; border:1px solid #E2E6F0; font-size:14px;'>" + receipt.getNotes() + "</td></tr>" : "",
                receipt.getCreatedAt()
        );
    }
}